<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>English</string>
	<key>CFBundleExecutable</key>
	<string>qdigidocclient</string>
	<key>CFBundleIconFile</key>
	<string>Icon.icns</string>
	<key>CFBundleIdentifier</key>
	<string>org.esteid.qdigidocclient</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>qdigidocclient</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>0.1.@PROJECT_WC_REVISION@</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>@PROJECT_WC_REVISION@</string>
	<key>LSEnvironment</key>
	<dict>
		<key>BDOCLIB_CONF_XML</key>
		<string>/usr/local/etc/digidocpp/digidocpp.conf</string>
	</dict>
	<key>LSHasLocalizedDisplayName</key>
	<true/>
	<key>CFBundleDocumentTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeExtensions</key>
			<array>
				<string>bdoc</string>
			</array>
			<key>CFBundleTypeIconFile</key>
			<string>bdoc.icns</string>
			<key>CFBundleTypeMIMETypes</key>
			<array>
				<string>application/bdoc</string>
			</array>
			<key>CFBundleTypeOSTypes</key>
			<array>
				<string>BDOC</string>
			</array>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>LSIsAppleDefaultForType</key>
			<true/>
		</dict>
		<dict>
			<key>CFBundleTypeExtensions</key>
			<array>
				<string>ddoc</string>
			</array>
			<key>CFBundleTypeIconFile</key>
			<string>ddoc.icns</string>
			<key>CFBundleTypeMIMETypes</key>
			<array>
				<string>application/ddoc</string>
			</array>
			<key>CFBundleTypeOSTypes</key>
			<array>
				<string>DDOC</string>
			</array>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>LSIsAppleDefaultForType</key>
			<true/>
		</dict>
		<dict>
			<key>CFBundleTypeExtensions</key>
			<array>
				<string>p12d</string>
			</array>
			<key>CFBundleTypeIconFile</key>
			<string>p12d.icns</string>
			<key>CFBundleTypeMIMETypes</key>
			<array>
				<string>application/x-p12d</string>
			</array>
			<key>CFBundleTypeOSTypes</key>
			<array>
				<string>P12D</string>
			</array>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>LSIsAppleDefaultForType</key>
			<true/>
		</dict>
		<dict>
			<key>CFBundleTypeExtensions</key>
			<array>
				<string>*</string>
			</array>
			<key>CFBundleTypeOSTypes</key>
			<array>
				<string>****</string>
			</array>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>LSHandlerRank</key>
			<string>None</string>
		</dict>
	</array>
</dict>
</plist>
