<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>English</string>
	<key>CFBundleExecutable</key>
	<string>${APPLE_GUI_IDENTIFIER}</string>
	<key>CFBundleGetInfoString</key>
	<string>${APPLE_GUI_INFO_STRING}</string>
	<key>CFBundleIconFile</key>
	<string>${APPLE_GUI_ICON}</string>
	<key>CFBundleIdentifier</key>
	<string>${APPLE_GUI_IDENTIFIER}</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleLongVersionString</key>
	<string>${APPLE_GUI_LONG_VERSION_STRING}</string>
	<key>CFBundleName</key>
	<string>${APPLE_GUI_BUNDLE_NAME}</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>${APPLE_GUI_SHORT_VERSION_STRING}</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>${APPLE_GUI_BUNDLE_VERSION}</string>
	<key>CSResourcesFileMapped</key>
	<true/>
	<key>LSRequiresCarbon</key>
	<true/>
	<key>NSHumanReadableCopyright</key>
	<string>${APPLE_GUI_COPYRIGHT}</string>
	<key>LSEnvironment</key>
	<dict>
		<key>DIGIDOCPP_OVERRIDE_CONF</key>
		<string>${LIBDIGIDOCPP_CONF}</string>
	</dict>
	<key>LSHasLocalizedDisplayName</key>
	<true/>
	<key>CFBundleDocumentTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeExtensions</key>
			<array>
				<string>bdoc</string>
			</array>
			<key>CFBundleTypeIconFile</key>
			<string>bdoc.icns</string>
			<key>CFBundleTypeMIMETypes</key>
			<array>
				<string>application/bdoc</string>
			</array>
			<key>CFBundleTypeOSTypes</key>
			<array>
				<string>BDOC</string>
			</array>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>LSIsAppleDefaultForType</key>
			<true/>
		</dict>
		<dict>
			<key>CFBundleTypeExtensions</key>
			<array>
				<string>ddoc</string>
			</array>
			<key>CFBundleTypeIconFile</key>
			<string>ddoc.icns</string>
			<key>CFBundleTypeMIMETypes</key>
			<array>
				<string>application/ddoc</string>
			</array>
			<key>CFBundleTypeOSTypes</key>
			<array>
				<string>DDOC</string>
			</array>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>LSIsAppleDefaultForType</key>
			<true/>
		</dict>
		<dict>
			<key>CFBundleTypeExtensions</key>
			<array>
				<string>p12d</string>
			</array>
			<key>CFBundleTypeIconFile</key>
			<string>p12d.icns</string>
			<key>CFBundleTypeMIMETypes</key>
			<array>
				<string>application/x-p12d</string>
			</array>
			<key>CFBundleTypeOSTypes</key>
			<array>
				<string>P12D</string>
			</array>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>LSIsAppleDefaultForType</key>
			<true/>
		</dict>
		<dict>
			<key>CFBundleTypeExtensions</key>
			<array>
				<string>*</string>
			</array>
			<key>CFBundleTypeOSTypes</key>
			<array>
				<string>****</string>
			</array>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>LSHandlerRank</key>
			<string>None</string>
		</dict>
	</array>
</dict>
</plist>
